flaskfilled/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask.ext.login import UserMixin, current_user
from flask.ext.principal import identity_loaded, RoleNeed, UserNeed

from flaskfilled import db, login_manager


class Cookie(db.Model):
    __tablename__ = 'cookies'

    cookie_id = db.Column(db.Integer(), primary_key=True)
    cookie_name = db.Column(db.String(50), index=True)
    cookie_recipe_url = db.Column(db.String(255))
    quantity = db.Column(db.Integer())


roles_users = db.Table('roles_users',
                       db.Column('user_id', db.Integer(),
                                 db.ForeignKey('users.user_id')),
                       db.Column('role_id', db.Integer(),
                                 db.ForeignKey('roles.id')))


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))


class User(db.Model, UserMixin):
    __tablename__ = 'users'

    user_id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(50))
    password = db.Column(db.String(50))
    password_hash = db.Column(db.String(255))
    authenticated = db.Column(db.Boolean, default=False)
    roles = db.relationship('Role', secondary=roles_users,
                            primaryjoin=user_id == roles_users.c.user_id,
                            backref='users')

    def get_id(self):
        return self.user_id

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)


@login_manager.user_loader
def load_user(userid):
    return User.query.get(userid)


@identity_loaded.connect
def on_identity_loaded(sender, identity):
    # Set the identity user object
    identity.user = current_user

    # Add the UserNeed to the identity
    if hasattr(current_user, 'id'):
        identity.provides.add(UserNeed(current_user.id))

    # Assuming the User model has a list of roles, update the
    # identity with the roles that the user provides
    if hasattr(current_user, 'roles'):
        for role in current_user.roles:
            identity.provides.add(RoleNeed(role.name))

flaskfilled/__init__.py
from flask import Flask
from flask.ext.login import LoginManager
from flask.ext.mail import Mail
from flask.ext.principal import Principal
from flask.ext.sqlalchemy import SQLAlchemy

from config import config

db = SQLAlchemy()
login_manager = LoginManager()
principal = Principal()
mail = Mail()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    db.init_app(app)
    login_manager.setup_app(app)
    principal.init_app(app)
    mail.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

flaskfilled/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

flaskfilled/main/views.py
from flask import render_template
from flask_mail import Message

from . import main
from flaskfilled.auth import admin_permission


@main.route('/', methods=['GET'])
def index():
    return render_template('main/index.html')


@main.route('/settings', methods=['GET'])
@admin_permission.require()
def settings():
    return render_template('main/settings.html')


@main.route('/mailme', methods=['GET'])
def mail():
    msg = Message('COOKIES!',
                  sender='from@example.com',
                  recipients=['to@example.com'])
    msg.body = 'There all mine!'
    msg.html = '<b>There all mine!</b>'
    mail.send(msg)

flaskfilled/templates/base.html
<html>
<head>
{% block head %} {% endblock %}
</head>
<body>
  <h1>{% block title %}App{% endblock %}</h1>
{% if current_user.is_authenticated() %}
  Hi {{ current_user.username }}!
{% endif %}
{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{% endblock %}
</body>
</html>

flaskfilled/templates/main/index.html
{% extends "base.html" %}

{% block title %}The Index{% endblock %}

{% block page_content %}
{% if not current_user.is_authenticated() %}
  <p><a href="{{ url_for('auth.login') }}">Click here to login</a>.</p>
{% else %}
  <p><a href="{{ url_for('main.settings') }}">Settings</a> - Admin only </p>
  <p><a href="{{ url_for('auth.logout') }}">Click here to logout</a>.</p>
{% endif %}
{% endblock %}

flaskfilled/templates/main/settings.html
{% extends "base.html" %}

{% block title %}Settings{% endblock %}

{% block page_content %}
Welcome Admin
{% endblock %}